algoritmo "Maior ou menor que 10"
// Função :  auto explicativo
// Autor :    Carolina
// Data : 18/05/2023
// Seção de Declarações 
var
numero: real

inicio

//inicio
escreval ("Digite o número:")
leia(numero)

//processamento

se(numero>10)entao

   escreval ("O número é maior que 10")

senao

   escreval ("O número é menor que 10")

fimse




// Seção de Comandos 
fimalgoritmo
