algoritmo "Maior de idae ou não"
// Função :Auto explicativo
// Autor : Carolina
// Data : 18/05/2023
// Seção de Declarações 
var
nome: caractere
idade: real


inicio

escreval ("Qual o seu nome?")
leia (nome)
escreval("Digite sua idade?")
leia (idade)

//processamento

se (idade>=18) entao
   escreval (nome, ", você é maior de idade!")

senao
escreval ( nome, ",você é menor de idade :(")

fimse
// Seção de Comandos 
fimalgoritmo
