algoritmo "Intervalo numérico"
// Função : Falar o intervalo de um número
// Autor : Carolina
// Data : 24/05/2023
// Seção de Declarações 
var
 numero: real
 
inicio

escreval ("Digite o número:")
leia (numero)

//processamento

se ((numero>100) e (numero<200))entao
escreval ("O número esta entre o intevalo de 100 e 200")

senao
escreval ("O número não esta entre o intervalo de 100 e 200")

fimse


// Seção de Comandos
fimalgoritmo
