algoritmo "combustível"
// Diciplina: PA
//Professora: Cíntia
//Turma: A
// Data : 09/03/2023
// Nome: Carolina
var
Dist: real
Comb: real
Med : real

//ENTRADA
inicio
escreva ("Escreva a distância percorrida: ")
leia (Dist)
escreval ("Escreva a quantidade de combustível gasta: ")
leia (Comb)

//PROCESSAMENTO
Med <- Comb/Dist

// SAÍDA
escreval (" A média de combustível gasto é: "‚Med)
fimalgoritmo
