algoritmo "CustoEvenda"
// Diciplina:PA
// Professora : Cintia
//Turma: A
// Data : 02/03/2023
// Nome: Carolina
var
NomeP: caractere
Custo, Venda, Porcentagem : real

//ENTRADA
inicio
escreva ("Digite nome do produto: ")
leia (NomeP)
escreval (" Digite o valor do produto: ")
leia (Custo)

//PROCESSAMENTO
Porcentagem <- Custo*0.65
Venda <- porcentagem * custo

// SAÍDA
escreval ("O valor da venda do produto é:", Venda)

fimalgoritmo
