algoritmo "Gasolina viagem"
// Fun??o :
// Autor :Carolina
// Data : 30/03/2023
// Se??o de Declara??es
var
//entrada
quilo,cons ,preco,media,valorf: real

inicio
//processamento
escreval ("Digite quilo")
leia (quilo)
escreval ("Digite consumo")
leia (cons)
escreval ("Digite preço da gasolina")
leia (preco)

//processamento
media <- quilo/cons
valorf <- media*preco

//sa?da

escreval ("Seu gasto é de: ", valorf)
// Se??o de Comandos
fimalgoritmo
