algoritmo "Hora e minuto para segundo"
// Função :
// Autor :Carolina
// Data : 30/03/2023
// Seção de Declarações
var
 hora, min, resulMin,convert: real
inicio
//estrada

escreval ("Digite a hora")
leia (hora)

escreval ("Digite os minutros")
leia (min)

//processamento
resulMin <- min/60
convert <- hora+ resulMin

//saída
escreval ("Horas convertido em decimal; ",convert)
// Seção de Comandos 

fimalgoritmo
