algoritmo "Hora e minuto para segundo"
// Fun??o :
// Autor :Carolina
// Data : 30/03/2023
// Se??o de Declara??es
var
 hora, min, resulMin,convert: real
inicio
//estrada

escreval ("Digite a hora")
leia (hora)

escreval ("Digite os minutros")
leia (min)

//processamento
resulMin <- min/60
convert <- hora+ resulMin

//sa?da
escreval ("Horas convertido em decimal; ",convert)
// Se??o de Comandos

fimalgoritmo
