algoritmo "Gasolina viagem"
// Função :
// Autor :Carolina
// Data : 30/03/2023
// Seção de Declarações 
var
//entrada
quilo,cons ,preço,média,valorf: real

inicio
//processamento
escreval ("Digite quilo")
leia (quilo)
escreval ("Digite consumo")
leia (cons)
escreval ("Digite preço da gasolina")
leia (preço)

//processamento
média <- quilo/cons
valorf <- média*preço

//saída

escreval ("Seu gasto é de: ", valorf)
// Seção de Comandos
fimalgoritmo
